name: Generates bookmarks HTML file

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-bookmarks:
    runs-on: ubuntu-latest
    steps:
      - name: Run static-marks
        uses: ksclarke/static-marks-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
